language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install
script: echo "Deploying!"
before_deploy: npm run build
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: df17
  project: devfestizmir17
  token:
    secure: BMfXazkNsielS9Y6X0uzs6C9ZH83BkegdUoNDn/HquUW8P6oJpxnZAJEUBxCZSUqkU9tPkdraPBJ7HaNhu1f/zvgNmADiykM42Ep84t4GfnolS+mw85e80dS2C9Q7kbNHtWLe5hEVNm0ncnAoMz/fVeypAx6+QcU5WBqvvrPVBy77PmhTorBChwSpRLgqe8io7J+d+EiUh1xvcy1cnHT4O6yU61tRB8BQgYoWSiIVhnh7bhuxNFq1vpx6QSMkqOEilkL+t6FK3nBdnZnTsldv88mtkIYhjmGI9OC+Xvs66HgZkDCBsQCXO7dxnCcZjdjZPoOT3Up8mHzBMo23lvXmT09qUzgrA0FLRc2c58odEO696bXnXXHqpvzLNPexgC52dO63xkeVW7/pEPzXAhij4rCfwstyDUebaMBS3lmZAVDhNI8dYwDLNmNaDpci+4XUWSqOb55A9vwcfIBO3UhCeiUVy18sD2HrHXJuP557Fe4Pd5DfuG0GfCcc4JEqj4IanIzmE7NwNYOO388vRVrhbLfOCJ6tZNDQ4UtaXmLWzc79Z903BK6QoYzy2A+ZQD5GZFKGXy+pidHRLaat5abJ1aNp10mIAaHnImObKACfqJYyeo3JadG+OX7RyQ20297I8g2a5FQZAwVK/0Z7J5yb2NCHl2yxyu7zOdINAiA31w=
# - provider: firebase
#   skip_cleanup: true
  # on:
  #   branch: develop
  # project: hoverboard-dev
  # token:
  #   secure: Quq/Ys1GKDYFjqMCD107saKj005L0RaM7Ian9yLIW/er4KdMzwjYw7TVXmtMeJPIfEy/e2/4WJ63K1SaXieBoFndoUcpGWqPOoTrnkkj5K7tzeZKM32XqIarF+BNmOoqW5M7+kuN8L7N3RLp00ywFDOgKgiZJeoaDV6sIRRAIFVh+xHWabVWpFCwCUSeBZpufOsZhMXkicyRe0XhMmkUvS1P5CI3AyZZdIfWG+sguFsPOWRjMFKWrbnsilDFDjf7N0Wd8Z1H2Z0LBn/V00bNb95MSIuOhkdk3a1wP0P5Eollet+Y8g+NpdWyFq0/C+6+ECvFLBjtvbtMY1BVfdxkCo5XlogZx31OmkMWVX6PXOD5Va8aFoJnwvjovUT8oZbSCWEuyMxI91jDsLxXZt542MNfUfQ1Q2+SpUShdcRlwoV2c/XOYvme95HnI1LSqzLubooKWxz8wpa/aovkdZbum54t/z5nA54AXN1lYKsi+hcAFHOeucqd/kHOLG0bx05Ev86wcvNH8qGx+v7S644YH37No7PGnKU3g3Jq/m6quo1B/bMEIaatVnR40D301wAi8tsNWnqEdWFKnAlGrTIDd1qek9OHnApmgBQI8o0FOy6WbzLMwl9PnMl+t+wew/ggSY0IdWhjFWR/S1d6xML8cYHXHVpE0wxkat5ETbIYXlg=

